### ISSUE TITLE
Version out of date?

### ISSUE THREAD

**Issue by marick** [cpjk/canary#40]
I'm not yet really familiar with versioning in Elixir yet, but `mix hex.outdated` shows that all my top-level dependencies are up-to-date. But when I add `{:canary, "~> 0.14.1"}`, `mix deps.get` gives me this:

```
Failed to use "ecto" (version 2.0.2) because
  canary (version 0.14.1) requires ~> 1.1
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  Locked to 2.0.2 in your mix.lock
```

**Comment by cpjk** [comment]
From your `hex` output, it looks like Canary restricts ecto to version 1.X while phoenix_ecto requires 2.0.0-rc.

I've relaxed the Ecto version requirement to `>= 1.1.0`. This should fix the error.

Let me know if you have any other problems or questions!

**Comment by marick** [comment]
Thanks. I do still get this warning:

```
2034 $ mix compile
==> canada
warning: the dependency :canada requires Elixir "~> 1.0.0-rc1" but you are running on v1.3.0
Compiling 2 files (.ex)
```

**Comment by cpjk** [comment]
Unfortunately, that warning is caused by [Canada](https://github.com/jarednorman/canada), one of Canary's dependencies. It won't affect Canary's functionality though. 

There is an open [issue](https://github.com/jarednorman/canada/issues/8) on that project regarding this warning. That might be a good place to chime in to apply some pressure.

It looks like the warning can be eliminated by fetching Canada from the github repo instead of hex.pm, but for now I think it would be better to stick to published releases on hex for all dependencies for stability.
